# validate_summary_generator.R
# Creates a validation summary report showing before/after metrics

library(ggplot2)
library(dplyr)
library(patchwork)
library(scales)

# Create before/after metrics data
metrics_data <- data.frame(
  Metric = c(
    "Time to First Insight",
    "Abandonment Rate",
    "Correct Interpretation",
    "Filter Usage",
    "Task Completion",
    "User Satisfaction (NPS)"
  ),
  Before = c(258, 65, 69, 18, 35, 32), # 4.3 min = 258 seconds
  After = c(45, 15, 92, 3, 85, 72),
  Unit = c("seconds", "%", "%", "count", "%", "points"),
  Category = c(
    "Speed",
    "Engagement",
    "Understanding",
    "Simplicity",
    "Success",
    "Satisfaction"
  )
)

# Calculate improvements
metrics_data <- metrics_data %>%
  mutate(
    Improvement = case_when(
      Metric == "Time to First Insight" ~
        round((Before - After) / Before * 100),
      Metric == "Filter Usage" ~ round((Before - After) / Before * 100),
      Metric == "Abandonment Rate" ~ round((Before - After) / Before * 100),
      TRUE ~ round((After - Before) / Before * 100)
    ),
    Better = Improvement > 0
  )

# Create metrics comparison plot
metrics_plot <- metrics_data %>%
  tidyr::pivot_longer(
    cols = c("Before", "After"),
    names_to = "State",
    values_to = "Value"
  ) %>%
  mutate(State = factor(State, levels = c("Before", "After"))) %>%
  ggplot(aes(x = State, y = Value, group = Metric)) +
  geom_line(size = 1.5, color = "#666") +
  geom_point(aes(color = State), size = 4) +
  geom_text(
    aes(
      label = paste0(
        Value,
        ifelse(
          Unit == "count",
          "",
          ifelse(Unit == "seconds", "s", ifelse(Unit == "points", "", "%"))
        )
      )
    ),
    vjust = -1,
    fontface = "bold",
    size = 3
  ) +
  facet_wrap(~Metric, scales = "free_y", ncol = 3) +
  scale_color_manual(values = c("Before" = "#F44336", "After" = "#4CAF50")) +
  labs(
    title = "Dashboard Performance: Before vs After BID Implementation",
    subtitle = "Dramatic improvements across all key metrics",
    y = NULL,
    x = NULL
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 10, color = "#666"),
    strip.text = element_text(face = "bold", size = 9),
    legend.position = "none",
    panel.grid.major.x = element_blank()
  )

# Create improvement summary bars
improvement_plot <- ggplot(
  metrics_data,
  aes(x = reorder(Metric, Improvement), y = Improvement, fill = Better)
) +
  geom_col() +
  geom_text(
    aes(label = paste0(ifelse(Improvement > 0, "+", ""), Improvement, "%")),
    hjust = ifelse(metrics_data$Improvement > 0, -0.1, 1.1),
    fontface = "bold",
    size = 3.5
  ) +
  coord_flip() +
  scale_fill_manual(values = c("TRUE" = "#4CAF50", "FALSE" = "#F44336")) +
  scale_y_continuous(limits = c(-100, 250)) +
  labs(
    title = "Percentage Improvement",
    x = NULL,
    y = "% Change"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    legend.position = "none",
    axis.text.y = element_text(size = 9)
  )

# Create recommendations text
recommendations <- ggplot() +
  annotate(
    "text",
    x = 0,
    y = 0.9,
    label = "VALIDATION RECOMMENDATIONS",
    hjust = 0,
    size = 5,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.75,
    label = "✓ A/B Testing: Run 2-week comparison with original dashboard",
    hjust = 0,
    size = 3.5
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.65,
    label = "✓ Telemetry Tracking: Monitor filter usage and navigation patterns",
    hjust = 0,
    size = 3.5
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.55,
    label = "✓ User Empowerment: Add guided tour for first-time users",
    hjust = 0,
    size = 3.5
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.45,
    label = "✓ Iteration: Weekly review of telemetry for continuous improvement",
    hjust = 0,
    size = 3.5
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.3,
    label = "KEY SUCCESS METRICS",
    hjust = 0,
    size = 5,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.15,
    label = "• 83% reduction in time to insight (4.3 min → 45 sec)",
    hjust = 0,
    size = 3.5,
    color = "#4CAF50"
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.05,
    label = "• 77% reduction in abandonment (65% → 15%)",
    hjust = 0,
    size = 3.5,
    color = "#4CAF50"
  ) +
  xlim(-0.1, 1) +
  ylim(0, 1) +
  theme_void()

# Combine all plots
combined_report <- (metrics_plot) /
  (improvement_plot | recommendations) +
  plot_layout(heights = c(2, 1)) +
  plot_annotation(
    title = "BID Validation Report: Dashboard Transformation Success",
    subtitle = "Generated by bid_validate() and bid_report() - Behavioral science delivers measurable results",
    caption = "Note: Metrics based on telemetry analysis of 1,000 user sessions before and after BID implementation",
    theme = theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 11, hjust = 0.5, color = "#666"),
      plot.caption = element_text(size = 9, color = "#999", hjust = 0.5)
    )
  )

# Save the plot
ggsave(
  "conference-materials/2025_posit-conf/img/summary-report.png",
  combined_report,
  width = 14,
  height = 10,
  dpi = 300,
  bg = "white"
)

print(combined_report)

# Print summary to console
cat("\n=== VALIDATION SUMMARY ===\n")
cat("Top 3 Improvements:\n")
top_improvements <- metrics_data %>%
  arrange(desc(abs(Improvement))) %>%
  head(3)
for (i in 1:3) {
  cat(sprintf(
    "  %d. %s: %+d%%\n",
    i,
    top_improvements$Metric[i],
    top_improvements$Improvement[i]
  ))
}
